src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCs and Laptops</fullName>
                </value>
                <value>
                    <fullName>Smartphones and Smartwatches</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Computer Components</fullName>
                </value>
                <value>
                    <fullName>Peripherals</fullName>
                </value>
                <value>
                    <fullName>TV and Audio</fullName>
                </value>
                <value>
                    <fullName>Smarthome</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_Image__c</fullName>
        <label>Display Image</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warranty_in_Months__c</fullName>
        <label>Warranty in Months</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZK_RecentProductsController.cls
public with sharing class ZK_RecentProductsController {

    @AuraEnabled
    public static List<ZK_ProductsController.ProductData> getRecentlyViewed() {
        List<RecentlyViewed> recentProducts = [
                SELECT Id, Name FROM RecentlyViewed
                WHERE Type = 'Product2'
                AND LastViewedDate != null
                ORDER BY LastViewedDate DESC
                LIMIT 6
        ];

        List<Id> productsIds = new List<Id>();
        for (RecentlyViewed recentlyViewed : recentProducts) {
            productsIds.add(recentlyViewed.Id);
        }

        List<PricebookEntry> entries = [
                SELECT Id,Product2.Name,Product2.Warranty_in_Months__c,Product2.ProductCode,
                        Product2.Category__c,Product2.Display_Image__c,UnitPrice
                FROM PricebookEntry
                WHERE Pricebook2.IsStandard=true
                AND Pricebook2.IsActive=true
                AND Product2.Id IN :productsIds
        ];

        return ZK_ProductHelp.parseEntries(entries);
    }

}